spring.application.name=ocbs

# --- App------------------------------------------------------------------------------------
app.name=Open Source Core Banking System
app.short-name=OSCBS
app.secret-key=your_secret_key_for_jwt_or_encryption
spring.profiles.active=dev

# --- Server ------------------------------------------------------------------------------------
server.port=8080
server.address=localhost
server.servlet.context-path=/

# --- Database (PostgreSQL) ------------------------------------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/oscbs
spring.datasource.username=postgres
spring.datasource.password=postgres1
spring.datasource.driver-class-name=org.postgresql.Driver
# --- Database Backup --------------------------------
spring.database.backup=true
spring.database.backup.path=db_backups
spring.database.backup.pgdump-path=C:\\Program Files\\PostgreSQL\\17\\bin\\pg_dump.exe

# --- SMTP ------------------------------------------------------------------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_smtp_password
spring.mail.from=noreply@yourdomain.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- Twilio (SMS) ------------------------------------------------------------------------------------
twilio.account-sid=your_twilio_account_sid
twilio.auth-token=your_twilio_auth_token
twilio.phone-number=+1234567890
twilio.messaging-service-sid=your_messaging_service_sid

# --- Google OAuth2 ------------------------------------------------------------------------------------
spring.security.oauth2.client.registration.google.client-id=your_google_client_id.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=your_google_client_secret
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google


